services:
  - type: web
    name: lllit.bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python reservas_main.py"
    plan: free
    runtime: python3.12.7
    envVars:
      - key: PORT
        value: 5000