services:
  - type: web
    name: lllit.bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:$PORT reservas_main:app"
    plan: free
    runtime: python3.12.7
    envVars:
      - key: PORT
        value: 5000